#!/usr/bin/php

<?php

set_include_path("./lib:./lib/unit");
spl_autoload_register();

if (getmypid() != 1) {
//    exit("sorry, need to infect pid eins\n");
}

$manager = new manager();

// Contrary to some init implementations we believe logging is quite important
// and should probably be brought up first
$logger = $manager->logger;
$logger->mumbleQuietly("we have logging");

$manager->target;

echo "we don't really trust the logging though so we're gonna chuck something onto stdout too\n";
